In [172]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords,wordnet
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import pickle
import re

In [173]:
nltk.download("stopwords")
nltk.download("punkt")
nltk.download("wordnet")
nltk.download("punkt_tab")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HARIHARAN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HARIHARAN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HARIHARAN\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HARIHARAN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [174]:
df = pd.read_csv("megaGymDataset.csv")
df.head()

,Unnamed: 0,Title,Desc,Type,BodyPart,Equipment,Level,Rating,RatingDesc
0,0,Partner plank band row,The partner plank band row is an abdominal exe...,Strength,Abdominals,Bands,Intermediate,0.0,NaN
1,1,Banded crunch isometric hold,The banded crunch isometric hold is an exercis...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
2,2,FYR Banded Plank Jack,The banded plank jack is a variation on the pl...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
3,3,Banded crunch,The banded crunch is an exercise targeting the...,Strength,Abdominals,Bands,Intermediate,NaN,NaN
4,4,Crunch,The crunch is a popular core exercise targetin...,Strength,Abdominals,Bands,Intermediate,NaN,NaN

In [175]:
df.describe()

        Unnamed: 0       Rating
count  2918.000000  1031.000000
mean   1458.500000     5.919690
std     842.498368     3.584607
min       0.000000     0.000000
25%     729.250000     3.000000
50%    1458.500000     7.900000
75%    2187.750000     8.700000
max    2917.000000     9.600000

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2918 entries, 0 to 2917
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2918 non-null   int64
 1   Title       2918 non-null   object
 2   Desc        1368 non-null   object
 3   Type        2918 non-null   object
 4   BodyPart    2918 non-null   object
 5   Equipment   2886 non-null   object
 6   Level       2918 non-null   object
 7   Rating      1031 non-null   float64
 8   RatingDesc  862 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 205.3+ KB

In [177]:
df.isnull().sum()

Unnamed: 0       0
Title            0
Desc          1550
Type             0
BodyPart         0
Equipment       32
Level            0
Rating        1887
RatingDesc    2056
dtype: int64

In [178]:
df = df.dropna(subset = ["Desc"])

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1368 entries, 0 to 2916
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1368 non-null   int64
 1   Title       1368 non-null   object
 2   Desc        1368 non-null   object
 3   Type        1368 non-null   object
 4   BodyPart    1368 non-null   object
 5   Equipment   1359 non-null   object
 6   Level       1368 non-null   object
 7   Rating      595 non-null    float64
 8   RatingDesc  506 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 106.9+ KB

In [180]:
df["RatingDesc"].value_counts()

RatingDesc
Average    506
Name: count, dtype: int64

In [181]:
df = df.drop(columns = ["Unnamed: 0","Rating","RatingDesc"],axis = 1)

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1368 entries, 0 to 2916
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Title      1368 non-null   object
 1   Desc       1368 non-null   object
 2   Type       1368 non-null   object
 3   BodyPart   1368 non-null   object
 4   Equipment  1359 non-null   object
 5   Level      1368 non-null   object
dtypes: object(6)
memory usage: 74.8+ KB

In [183]:
df.isnull().sum()

Title        0
Desc         0
Type         0
BodyPart     0
Equipment    9
Level        0
dtype: int64

In [184]:
df[df["Equipment"].isna()]

,Title,Desc,Type,BodyPart,Equipment,Level
637,Decline oblique crunch,The decline oblique crunch is a popular bodywe...,Strength,Abdominals,NaN,Intermediate
638,Decline sit-up,The decline sit-up is a bodyweight core exerci...,Strength,Abdominals,NaN,Intermediate
639,Hanging Windshield Wiper,The hanging windshield wiper is an advanced ab...,Strength,Abdominals,NaN,Intermediate
1402,Glute ham raise-,The glute ham raise is an exercise targeting t...,Strength,Hamstrings,NaN,Beginner
1403,Lying hamstring stretch with band,The lying hamstring stretch with band is a sim...,Stretching,Hamstrings,NaN,Beginner
1406,Alternating lunge jump,The alternating lunge jump is an explosive bod...,Stretching,Hamstrings,NaN,Beginner
2421,Dumbbell lateral hop to sprint,The dumbbell lateral hop to sprint is a multi-...,Plyometrics,Quadriceps,NaN,Intermediate
2422,Smith machine lunge sprint,The Smith machine lunge sprint is a lower-body...,Strength,Quadriceps,NaN,Intermediate
2423,Sissy squat,The sissy squat is a bodyweight squat variatio...,Strength,Quadriceps,NaN,Intermediate

In [185]:
df.Equipment.unique()

array(['Bands', 'Barbell', 'Kettlebells', 'Dumbbell', 'Other', 'Cable',
       'Machine', 'Body Only', 'Medicine Ball', nan, 'Exercise Ball',
       'Foam Roll', 'E-Z Curl Bar'], dtype=object)

In [186]:
df.loc[637, "Equipment"] = "Body Only"
df.loc[638, "Equipment"] = "Body Only"
df.loc[639, "Equipment"] = "Body Only"
df.loc[1402, "Equipment"] = "Body Only"
df.loc[1403, "Equipment"] = "Bands"
df.loc[1406, "Equipment"] = "Body Only"
df.loc[2421, "Equipment"] = "Dumbbell"
df.loc[2422, "Equipment"] = "Other"
df.loc[2423, "Equipment"] = "Body Only"

In [187]:
df.Equipment.unique()

array(['Bands', 'Barbell', 'Kettlebells', 'Dumbbell', 'Other', 'Cable',
       'Machine', 'Body Only', 'Medicine Ball', 'Exercise Ball',
       'Foam Roll', 'E-Z Curl Bar'], dtype=object)

In [188]:
df.Title.value_counts()

Title
Seated Cable Rows                        3
Band-suspended kettlebell bench press    3
Seated rear delt fly                     2
Dumbbell step-up                         2
Arnold press                             2
                                        ..
AM Flat Bench Barbell Press              1
TBS Close-Grip Bench Press               1
Bench press                              1
Incline bench press                      1
TBS Skullcrusher                         1
Name: count, Length: 1359, dtype: int64

In [189]:
df.Desc.value_counts()

Desc
The barbell back squat is a popular compound movement that emphasizes building the lower-body muscle groups and overall strength. It's the classic way to start a leg day, and is a worthy centerpiece to a lower-body training program. The squat is a competitive lift in the sport of powerlifting, but is also a classic measurement of lower-body strength. With the barbell racked on the traps or upper back, the emphasis is placed on the posterior chain but the entire body gets worked. The back squat can be trained in everything from heavy singles to sets of 20 reps or higher.    10
The barbell stiff-legged deadlift targets the hamstrings, glutes, lower and upper back, as well as the core. It is a popular accessory movement for the deadlift, but also a muscle-building hamstring movement.                                                                                                                                                                                                                                                                                                                                                                                     6
The push-up is a popular bodyweight exercise that is commonly used in military and tactical physical fitness tests. It’s a classic movement to build upper-body muscle and strength, emphasizing the chest, triceps, and shoulders, but also working the upper back and core.                                                                                                                                                                                                                                                                                                                        6
The lat pull-down is a cable-based exercise machine that’s ubiquitous in gyms around the world. This back builder is easy to learn and highly effective, allowing for variable resistance depending on where you place the pin in the stack.                                                                                                                                                                                                                                                                                                                                                         6
The hack squat is a machine-based exercise that targets the muscles of the legs, particularly the quadriceps. It is often used as an accessory for squats, but can also be the main lower-body movement in a workout. It is often performed for moderate to high reps, such as 8-12 reps per set or more.                                                                                                                                                                                                                                                                                            6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
The wide push-up plank hold is a full-body exercise targeting the core. Because the arms aren't directly under the body, it can be more difficult than traditional push-up planks, especially for the upper back and chest, but also for the core.                                                                                                                                                                                                                                                                                                                                                   1
The chest dip is a chest-building exercise in which the lifter hangs between two parallel handles. Leaning the torso slightly forward shifts the emphasis from the triceps to the chest.                                                                                                                                                                                                                                                                                                                                                                                                             1
The scapular push-up is an upper-body exercise aimed at increasing the stability of the scapulae and mobility in the shoulders. It is often performed as part of a dynamic warm-up before an upper-body workout, or as part of a mobility session.                                                                                                                                                                                                                                                                                                                                                   1
The warrior push-up is a series of push-up and plank variations combined into a single sequence. They include a Judo push-up, plank, side plank, mountain climber, diamond push-up, and regular push-up. Done together, they tax the upper-body muscles from different angles and increase time under tension for the entire body.                                                                                                                                                                                                                                                                   1
The EZ-bar skullcrusher is a popular exercise targeting the triceps muscles. Contrary to what the name implies, the bar should actually come down behind the head. It is usually performed for moderate to high reps as part of an upper-body or arms-focused workout.                                                                                                                                                                                                                                                                                                                               1
Name: count, Length: 1050, dtype: int64

In [190]:
df = df.drop_duplicates(subset = ["Title"])

In [191]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1359 entries, 0 to 2916
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Title      1359 non-null   object
 1   Desc       1359 non-null   object
 2   Type       1359 non-null   object
 3   BodyPart   1359 non-null   object
 4   Equipment  1359 non-null   object
 5   Level      1359 non-null   object
dtypes: object(6)
memory usage: 74.3+ KB

In [192]:
df["Title"] = df["Title"].str.replace(
    r"^30\s+",
    "",
    regex=True
)

In [193]:
text_desc = "The barbell back squat is a popular compound movement that emphasizes building the lower-body muscle groups and overall strength. It's the classic way to start a leg day, and is a worthy centerpiece to a lower-body training program. The squat is a competitive lift in the sport of powerlifting, but is also a classic measurement of lower-body strength. With the barbell racked on the traps or upper back, the emphasis is placed on the posterior chain but the entire body gets worked. The back squat can be trained in everything from heavy singles to sets of 20 reps or higher."

In [194]:
df[df["Desc"]== text_desc]

,Title,Desc,Type,BodyPart,Equipment,Level
1799,Barbell Full Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1810,Barbell Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1822,Barbell back squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1849,Paul Carter Back Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1851,TBS High-Bar Back Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1853,Squat - Gethin Variation,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1857,Barbell Squat - Gethin Variation,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1859,AM Barbell Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1862,UP Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate
1867,King Maker Barbell Back Squat,The barbell back squat is a popular compound m...,Strength,Quadriceps,Barbell,Intermediate

In [195]:
df["Actual_desc"] = (
    df["Desc"].astype(str) + " | " +
    df["Type"].astype(str) + " | " +
    df["BodyPart"].astype(str) + " | " +
    df["Equipment"].astype(str) + " | " +
    df["Level"].astype(str)
)

In [196]:
df.shape

(1359, 7)

In [197]:
df = df.reset_index(drop = True)

In [198]:
df.head()

,Title,Desc,Type,BodyPart,Equipment,Level,Actual_desc
0,Partner plank band row,The partner plank band row is an abdominal exe...,Strength,Abdominals,Bands,Intermediate,The partner plank band row is an abdominal exe...
1,Banded crunch isometric hold,The banded crunch isometric hold is an exercis...,Strength,Abdominals,Bands,Intermediate,The banded crunch isometric hold is an exercis...
2,FYR Banded Plank Jack,The banded plank jack is a variation on the pl...,Strength,Abdominals,Bands,Intermediate,The banded plank jack is a variation on the pl...
3,Banded crunch,The banded crunch is an exercise targeting the...,Strength,Abdominals,Bands,Intermediate,The banded crunch is an exercise targeting the...
4,Crunch,The crunch is a popular core exercise targetin...,Strength,Abdominals,Bands,Intermediate,The crunch is a popular core exercise targetin...

In [199]:
df["Actual_desc"][1]

'The banded crunch isometric hold is an exercise targeting the abdominal muscles, particularly the rectus abdominis or "six-pack" muscles. The band adds resistance and continuous tension to this popular exercise. | Strength | Abdominals | Bands | Intermediate'

In [200]:
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [201]:
def clean(text):
    tokens = word_tokenize(text.lower())
    processed_tokens = []
    for token in tokens:
        if token.isalpha() and token not in stop_words:
            stemmed_token = stemmer.stem(token)
            lemmatized_token  = lemmatizer.lemmatize(stemmed_token)
            processed_tokens.append(lemmatized_token)

    return " ".join(processed_tokens)

In [202]:
df["Actual_desc"] = df["Actual_desc"].apply(clean)

In [203]:
df.head()

,Title,Desc,Type,BodyPart,Equipment,Level,Actual_desc
0,Partner plank band row,The partner plank band row is an abdominal exe...,Strength,Abdominals,Bands,Intermediate,partner plank band row abdomin exercis two par...
1,Banded crunch isometric hold,The banded crunch isometric hold is an exercis...,Strength,Abdominals,Bands,Intermediate,band crunch isometr hold exercis target abdomi...
2,FYR Banded Plank Jack,The banded plank jack is a variation on the pl...,Strength,Abdominals,Bands,Intermediate,band plank jack variat plank involv move leg r...
3,Banded crunch,The banded crunch is an exercise targeting the...,Strength,Abdominals,Bands,Intermediate,band crunch exercis target abdomin muscl parti...
4,Crunch,The crunch is a popular core exercise targetin...,Strength,Abdominals,Bands,Intermediate,crunch popular core exercis target rectu abdom...

In [204]:
df["Actual_desc"][1]

'band crunch isometr hold exercis target abdomin muscl particularli rectu abdomini muscl band add resist continu tension popular exercis strength abdomin band intermedi'

In [205]:
#Vectorizer = CountVectorizer(stop_words = "english")
#vectors = Vectorizer.fit_transform(df["Actual_desc"]).toarray()

In [206]:
Cleaned_df = df[["Title","Actual_desc"]]

In [207]:
Vectorizer = CountVectorizer(stop_words = "english")
vectors = Vectorizer.fit_transform(Cleaned_df["Actual_desc"]).toarray()

In [208]:
vectors

array([[0, 0, 2, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [209]:
vectors.shape

(1359, 1280)

In [210]:
similarity = cosine_similarity(vectors)

In [211]:
similarity[0]

array([1.        , 0.53526436, 0.50832857, ..., 0.2245251 , 0.19179882,
       0.19179882])

In [212]:
Vectorizer.get_feature_names_out(10)

array(['ab', 'abdomen', 'abdomin', ..., 'yoga', 'zercher', 'zero'],
      dtype=object)

In [213]:
def pred(title):
    index = Cleaned_df[Cleaned_df["Title"] == title].index[0]
    list_var = list(enumerate(similarity[index]))
    sorted_list = sorted(list_var ,key = lambda x:x[1] , reverse = True)
    top_five = sorted_list[1:6]

    for i in top_five:
        print (Cleaned_df.iloc[i[0]].Title)

In [214]:
Cleaned_df[Cleaned_df["Title"] == "Decline bar press sit-up"].index[0]

9

In [215]:
sorted(list(enumerate(similarity[0])),reverse = True,key = lambda x:x[1])

[(0, 1.0),
 (791, 0.9718253158075502),
 (585, 0.5527707983925667),
 (3, 0.5512459105263765),
 (1, 0.5352643613280605),
 (1271, 0.5266851623825876),
 (2, 0.5083285677753488),
 (6, 0.50709255283711),
 (838, 0.5),
 (1275, 0.47628967220784013),
 (181, 0.4720587952499556),
 (198, 0.4720587952499556),
 (314, 0.4719399037242694),
 (146, 0.46423834544262965),
 (123, 0.4622501635210242),
 (330, 0.4517812304569955),
 (1274, 0.4517812304569955),
 (153, 0.4422689813358516),
 (4, 0.4409585518440984),
 (128, 0.4409585518440984),
 (251, 0.4409585518440983),
 (793, 0.4383972994809528),
 (279, 0.4371928248925937),
 (289, 0.4371928248925937),
 (290, 0.4371928248925937),
 (130, 0.433289122413121),
 (131, 0.433289122413121),
 (176, 0.43259045634870014),
 (255, 0.4320792826090466),
 (272, 0.42426406871192845),
 (164, 0.4170288281141496),
 (124, 0.41666666666666674),
 (586, 0.41328414257736795),
 (682, 0.4132841425773679),
 (214, 0.41147559989891175),
 (860, 0.40857528153788336),
 (749, 0.39999999999999997),
 (163, 0.39440531887330776),
 (157, 0.3944053188733077),
 (1101, 0.3937807653241084),
 (5, 0.39317854974639227),
 (110, 0.3928371006591931),
 (117, 0.3928371006591931),
 (750, 0.3928371006591931),
 (226, 0.3891882645212855),
 (858, 0.38575837490522985),
 (861, 0.38575837490522985),
 (39, 0.3849001794597505),
 (859, 0.3841749099639162),
 (856, 0.3823595564509363),
 (174, 0.3823595564509362),
 (186, 0.3823595564509362),
 (680, 0.3812464258315117),
 (125, 0.3810003810005715),
 (284, 0.37862009270926794),
 (155, 0.3785166493051126),
 (242, 0.37796447300922714),
 (794, 0.3771682545706787),
 (161, 0.3742275995918744),
 (259, 0.37319524562623346),
 (132, 0.37267799624996495),
 (109, 0.3726779962499649),
 (118, 0.3715802678087691),
 (439, 0.3715802678087691),
 (113, 0.3689323936863109),
 (212, 0.3689323936863109),
 (250, 0.3689323936863109),
 (121, 0.36650833306891567),
 (1104, 0.36578176047514493),
 (144, 0.3651483716701107),
 (160, 0.3651483716701107),
 (178, 0.3646624787447364),
 (857, 0.36466247874473634),
 (45, 0.36288736930121157),
 (440, 0.3571428571428571),
 (1272, 0.35696644673093675),
 (221, 0.35634832254989923),
 (1099, 0.35619780582827415),
 (92, 0.35533452725935066),
 (93, 0.35533452725935066),
 (241, 0.35533452725935066),
 (208, 0.3517632353407243),
 (243, 0.3517632353407243),
 (792, 0.35176323534072423),
 (293, 0.3511234415883917),
 (256, 0.3481553119113957),
 (41, 0.3478327964999673),
 (54, 0.3478327964999673),
 (129, 0.34752402342845795),
 (147, 0.34752402342845795),
 (88, 0.3469443332443555),
 (203, 0.3469443332443555),
 (145, 0.3469443332443554),
 (287, 0.34668762264076813),
 (26, 0.34646743359179155),
 (102, 0.34646743359179155),
 (202, 0.34646743359179155),
 (1073, 0.3442651863295481),
 (105, 0.34403123102809324),
 (283, 0.3435921354681383),
 (1102, 0.3435921354681383),
 (1351, 0.34143167982105604),
 (288, 0.341431679821056),
 (44, 0.3404414533245951),
 (112, 0.3404414533245951),
 (185, 0.3404414533245951),
 (197, 0.3404414533245951),
 (28, 0.3403516468284207),
 (216, 0.3403516468284206),
 (89, 0.34020690871988585),
 (106, 0.34020690871988585),
 (183, 0.34020690871988585),
 (192, 0.34020690871988585),
 (194, 0.34020690871988585),
 (195, 0.34020690871988585),
 (201, 0.34020690871988585),
 (223, 0.34020690871988585),
 (312, 0.3402069087198858),
 (63, 0.3380617018914067),
 (73, 0.3380617018914067),
 (76, 0.3380617018914067),
 (862, 0.3380617018914066),
 (1103, 0.33678765702728175),
 (265, 0.3367876570272817),
 (62, 0.33333333333333337),
 (768, 0.33333333333333337),
 (190, 0.3333333333333333),
 (200, 0.3333333333333333),
 (268, 0.3333333333333333),
 (277, 0.3333333333333333),
 (258, 0.33333333333333326),
 (107, 0.32927638704908735),
 (235, 0.3292763870490873),
 (191, 0.32686022523030667),
 (199, 0.32686022523030667),
 (681, 0.32663728995924396),
 (313, 0.323575114464717),
 (69, 0.32338083338177726),
 (218, 0.3227486121839514),
 (34, 0.32075014954979214),
 (52, 0.3207501495497921),
 (100, 0.3207501495497921),
 (222, 0.3207501495497921),
 (276, 0.3207501495497921),
 (114, 0.31980107453341555),
 (11, 0.31945757166894373),
 (264, 0.31914236925211276),
 (1105, 0.31872762915583835),
 (188, 0.31622776601683794),
 (189, 0.31497039417435596),
 (219, 0.31497039417435596),
 (780, 0.3144140727612662),
 (1007, 0.3127716210856122),
 (1053, 0.3127716210856122),
 (1068, 0.3127716210856122),
 (1072, 0.3127716210856122),
 (9, 0.3123475237772122),
 (286, 0.3099937033168514),
 (134, 0.3098898934004561),
 (294, 0.30952380952380953),
 (292, 0.3095238095238095),
 (91, 0.30949223029508643),
 (239, 0.30949223029508643),
 (811, 0.30949223029508643),
 (1062, 0.3091420111676559),
 (168, 0.3042903097250923),
 (477, 0.30429030972509225),
 (1085, 0.30429030972509225),
 (196, 0.30339401820606876),
 (58, 0.30151134457776363),
 (150, 0.30151134457776363),
 (87, 0.3004626062886658),
 (295, 0.3004626062886657),
 (847, 0.3),
 (236, 0.2981423969999719),
 (1016, 0.2981423969999719),
 (1070, 0.2981423969999719),
 (261, 0.29761455522215957),
 (832, 0.2976145552221595),
 (275, 0.2948839123097942),
 (120, 0.294174202707276),
 (165, 0.2935682819759931),
 (101, 0.29356828197599305),
 (441, 0.2916666666666667),
 (617, 0.29166666666666663),
 (326, 0.29095718698132317),
 (621, 0.29095718698132317),
 (103, 0.2901294265928298),
 (98, 0.2898754521821015),
 (1273, 0.2895330120717931),
 (280, 0.2894143807081531),
 (291, 0.2894143807081531),
 (94, 0.2886751345948129),
 (613, 0.28867513459481287),
 (852, 0.28867513459481287),
 (938, 0.28867513459481287),
 (1248, 0.28867513459481287),
 (273, 0.28631856346244444),
 (254, 0.2858309752375147),
 (143, 0.28583097523751466),
 (172, 0.28583097523751466),
 (179, 0.28583097523751466),
 (224, 0.28583097523751466),
 (1100, 0.2855287176446869),
 (55, 0.2844972711960655),
 (789, 0.2844972711960655),
 (587, 0.28426762180748055),
 (588, 0.28426762180748055),
 (591, 0.28426762180748055),
 (622, 0.28426762180748055),
 (1088, 0.28426762180748055),
 (159, 0.28347335475692037),
 (1009, 0.28347335475692037),
 (231, 0.282842712474619),
 (1098, 0.28266610133502934),
 (7, 0.282075973791785),
 (8, 0.282075973791785),
 (13, 0.282075973791785),
 (15, 0.282075973791785),
 (220, 0.28171808490950556),
 (257, 0.2795807122764419),
 (769, 0.2795807122764419),
 (1057, 0.27801921874276636),
 (16, 0.2777777777777778),
 (95, 0.2773500981126145),
 (187, 0.2773500981126145),
 (237, 0.2773500981126145),
 (71, 0.27638539919628335),
 (43, 0.27399831217559545),
 (56, 0.27399831217559545),
 (175, 0.27399831217559545),
 (737, 0.27399831217559545),
 (72, 0.2721655269759087),
 (247, 0.2721655269759087),
 (824, 0.2721655269759087),
 (1117, 0.2721655269759087),
 (1125, 0.2721655269759087),
 (1235, 0.2721655269759087),
 (1238, 0.2721655269759087),
 (1318, 0.2721655269759087),
 (1322, 0.2721655269759087),
 (1324, 0.2721655269759087),
 (1327, 0.2721655269759087),
 (1330, 0.2721655269759087),
 (918, 0.2708333333333333),
 (51, 0.27036903521793754),
 (142, 0.27036903521793754),
 (166, 0.27036903521793754),
 (167, 0.27036903521793754),
 (170, 0.27036903521793754),
 (229, 0.27036903521793754),
 (245, 0.27036903521793754),
 (855, 0.27036903521793754),
 (162, 0.26940795304016235),
 (180, 0.26940795304016235),
 (64, 0.2672612419124244),
 (137, 0.2672612419124244),
 (599, 0.2672612419124244),
 (399, 0.2668802563418119),
 (115, 0.26688025634181184),
 (111, 0.2666982304552209),
 (910, 0.2666982304552209),
 (99, 0.26666666666666666),
 (169, 0.26666666666666666),
 (309, 0.26666666666666666),
 (1025, 0.26666666666666666),
 (230, 0.26490647141300877),
 (608, 0.26490647141300877),
 (37, 0.26470046277199466),
 (1270, 0.2646188733785785),
 (478, 0.26352313834736496),
 (853, 0.26352313834736496),
 (1139, 0.262746927122694),
 (18, 0.26190476190476186),
 (47, 0.26148818018424536),
 (104, 0.26148818018424536),
 (171, 0.26148818018424536),
 (238, 0.26148818018424536),
 (253, 0.26148818018424536),
 (848, 0.2611164839335468),
 (988, 0.2611164839335468),
 (116, 0.2608745973749754),
 (266, 0.2592724864350674),
 (777, 0.2581988897471611),
 (782, 0.2581988897471611),
 (784, 0.2581988897471611),
 (785, 0.2581988897471611),
 (798, 0.2581988897471611),
 (355, 0.2578553115646983),
 (59, 0.25724787771376323),
 (215, 0.25724787771376323),
 (1052, 0.25724787771376323),
 (182, 0.25717224993681986),
 (1335, 0.25717224993681986),
 (1156, 0.2567180154051351),
 (1161, 0.25660011963983365),
 (285, 0.25607375986579195),
 (873, 0.25607375986579195),
 (85, 0.2542375899365633),
 (810, 0.2542375899365633),
 (68, 0.2541642838876744),
 (701, 0.253546276418555),
 (126, 0.2519763153394848),
 (207, 0.2519763153394848),
 (308, 0.2519763153394848),
 (489, 0.2519763153394848),
 (975, 0.2519763153394848),
 (987, 0.2519763153394848),
 (1087, 0.2519763153394848),
 (1249, 0.2519763153394848),
 (1250, 0.2519763153394848),
 (1287, 0.2519763153394848),
 (1291, 0.2519763153394848),
 (74, 0.251259453814803),
 (274, 0.251259453814803),
 (17, 0.25),
 (1067, 0.25),
 (1313, 0.25),
 (1323, 0.25),
 (1326, 0.25),
 (1329, 0.25),
 (1034, 0.24999999999999997),
 (1126, 0.24999999999999997),
 (920, 0.24948506639458295),
 (82, 0.24873416908154544),
 (592, 0.24873416908154544),
 (745, 0.24873416908154544),
 (1059, 0.24759378423606915),
 (1071, 0.24759378423606915),
 (1314, 0.24759378423606915),
 (886, 0.24720661623652213),
 (897, 0.24720661623652213),
 (1185, 0.2472066162365221),
 (57, 0.24720661623652207),
 (1217, 0.24659848095803594),
 (60, 0.2465984809580359),
 (498, 0.2465984809580359),
 (1060, 0.24618298195866545),
 (1286, 0.24618298195866542),
 (49, 0.2457365935914952),
 (593, 0.2457365935914952),
 (38, 0.2449894717530557),
 (311, 0.2449894717530557),
 (877, 0.24343224778007383),
 (984, 0.24343224778007383),
 (992, 0.24343224778007383),
 (1003, 0.24343224778007383),
 (700, 0.2434322477800738),
 (339, 0.24333213169614382),
 (376, 0.24333213169614382),
 (577, 0.2433321316961438),
 (1151, 0.2433321316961438),
 (1169, 0.2433321316961438),
 (1190, 0.2433321316961438),
 (1191, 0.2433321316961438),
 (1196, 0.2433321316961438),
 (1276, 0.24333213169614376),
 (80, 0.24326681639992057),
 (184, 0.24326681639992057),
 (225, 0.24326681639992057),
 (246, 0.24326681639992057),
 (1020, 0.24326681639992057),
 (158, 0.24310831916315753),
 (193, 0.24310831916315753),
 (639, 0.24253562503633297),
 (336, 0.24072846024282465),
 (353, 0.24072846024282465),
 (834, 0.2405626121623441),
 (42, 0.24056261216234406),
 (823, 0.24056261216234406),
 (301, 0.24019223070763068),
 (122, 0.23947373603569988),
 (471, 0.23947373603569988),
 (1308, 0.23947373603569982),
 (300, 0.2381448361039201),
 (605, 0.2381448361039201),
 (232, 0.23809523809523808),
 (1263, 0.23809523809523808),
 (1245, 0.23735633163877062),
 (206, 0.23717082451262844),
 (688, 0.23717082451262844),
 (1005, 0.23717082451262844),
 (1069, 0.23717082451262844),
 (1112, 0.23717082451262844),
 (1167, 0.23717082451262844),
 (1176, 0.23717082451262844),
 (1236, 0.23717082451262844),
 (451, 0.23622779563076698),
 (25, 0.23570226039551584),
 (50, 0.23570226039551584),
 (210, 0.23570226039551584),
 (260, 0.23570226039551584),
 (1232, 0.23570226039551584),
 (1240, 0.23570226039551584),
 (1244, 0.23570226039551584),
 (1058, 0.2357022603955158),
 (240, 0.2342606428329091),
 (267, 0.2342606428329091),
 (374, 0.2342606428329091),
 (549, 0.23338001400466826),
 (501, 0.23333333333333334),
 (1039, 0.23333333333333334),
 (1348, 0.23333333333333334),
 (391, 0.2333333333333333),
 (394, 0.2333333333333333),
 (878, 0.2328335661670159),
 (1130, 0.2328335661670159),
 (86, 0.23249527748763854),
 (820, 0.2321035412742638),
 (828, 0.2321035412742638),
 (951, 0.2321035412742638),
 (1299, 0.2321035412742638),
 (822, 0.23145502494313785),
 (1150, 0.23145502494313785),
 (1172, 0.23145502494313785),
 (732, 0.2311250817605121),
 (742, 0.2311250817605121),
 (335, 0.22966620733471135),
 (496, 0.22941573387056174),
 (609, 0.22941573387056174),
 (96, 0.22916666666666666),
 (227, 0.22916666666666666),
 (66, 0.22893427324781504),
 (228, 0.22893427324781504),
 (249, 0.22893427324781504),
 (610, 0.22893427324781504),
 (684, 0.22893427324781504),
 (1021, 0.22880215766121467),
 (486, 0.22880215766121464),
 (891, 0.22866478019001174),
 (1063, 0.2286647801900117),
 (269, 0.22739701341354887),
 (1320, 0.22727272727272724),
 (67, 0.22680460581325723),
 (75, 0.22680460581325723),
 (77, 0.22680460581325723),
 (761, 0.22680460581325723),
 (842, 0.22680460581325723),
 (84, 0.22645540682891913),
 (637, 0.22613350843332272),
 (840, 0.22613350843332272),
 (1114, 0.22613350843332272),
 (1321, 0.22613350843332272),
 (1354, 0.22613350843332272),
 (567, 0.22566773346210997),
 (837, 0.22566773346210997),
 (97, 0.2253744679276044),
 (414, 0.2253744679276044),
 (1147, 0.2253744679276044),
 (1228, 0.2253744679276044),
 (1230, 0.2253744679276044),
 (872, 0.2247332874877474),
 (213, 0.22452510468485448),
 (1011, 0.22452510468485448),
 (1035, 0.22452510468485448),
 (1356, 0.22452510468485448),
 (444, 0.22452510468485443),
 (541, 0.22452510468485443),
 (546, 0.22452510468485443),
 (788, 0.22452510468485443),
 (850, 0.22452510468485443),
 (851, 0.22452510468485443),
 (854, 0.22452510468485443),
 (263, 0.22397731465322626),
 (156, 0.22360679774997896),
 (925, 0.22360679774997894),
 (940, 0.22360679774997894),
 (1064, 0.22360679774997894),
 (405, 0.22271770159368698),
 (675, 0.22232432294997184),
 (119, 0.2222222222222222),
 (495, 0.2222222222222222),
 (655, 0.2222222222222222),
 (660, 0.2222222222222222),
 (976, 0.2222222222222222),
 (985, 0.2222222222222222),
 (998, 0.2222222222222222),
 (1189, 0.2222222222222222),
 (1301, 0.2222222222222222),
 (1306, 0.2222222222222222),
 (299, 0.2204792759220492),
 (956, 0.2204792759220492),
 (1285, 0.2204792759220492),
 (24, 0.22047927592204916),
 (35, 0.22047927592204916),
 (420, 0.21919864974047637),
 (430, 0.21919864974047637),
 (813, 0.21919864974047637),
 (1154, 0.21919864974047637),
 (1243, 0.21919864974047637),
 (728, 0.21912524504463887),
 (83, 0.21884405476620425),
 (278, 0.21884405476620425),
 (1311, 0.21884405476620425),
 (1155, 0.21884405476620422),
 (1262, 0.2187974872468418),
 (79, 0.2182178902359924),
 (1166, 0.21698151830137316),
 (1315, 0.21698151830137316),
 (1242, 0.21698151830137313),
 (1018, 0.2166445612065605),
 (741, 0.2165063509461097),
 (369, 0.21650635094610968),
 (318, 0.21629522817435004),
 (328, 0.21629522817435004),
 (329, 0.21629522817435004),
 (337, 0.21629522817435004),
 (354, 0.21629522817435004),
 (360, 0.21629522817435004),
 (371, 0.21629522817435004),
 (839, 0.21629522817435004),
 (687, 0.21629522817435),
 (1066, 0.21629522817435),
 (653, 0.2160604053625562),
 (1247, 0.2160604053625562),
 (29, 0.21516574145596756),
 (744, 0.21428571428571427),
 (1293, 0.21428571428571427),
 (419, 0.2135042050734495),
 (1145, 0.21348801026893016),
 (70, 0.2132007163556104),
 (554, 0.2132007163556104),
 (133, 0.2130032168075646),
 (340, 0.2130032168075646),
 (691, 0.2130032168075646),
 (693, 0.2130032168075646),
 (695, 0.2130032168075646),
 (812, 0.2130032168075646),
 (816, 0.2130032168075646),
 (989, 0.2130032168075646),
 (994, 0.2130032168075646),
 (1260, 0.2130032168075646),
 (476, 0.21300321680756457),
 (946, 0.21300321680756457),
 (1295, 0.21245914639969937),
 (151, 0.21081851067789195),
 (709, 0.21081851067789195),
 (797, 0.21081851067789195),
 (802, 0.21081851067789195),
 (803, 0.21081851067789195),
 (952, 0.21081851067789195),
 (1237, 0.21081851067789195),
 (1307, 0.21081851067789195),
 (795, 0.21004201260420147),
 (685, 0.21004201260420144),
 (815, 0.21004201260420144),
 (997, 0.2095395190312374),
 (332, 0.20953951903123735),
 (411, 0.20953951903123735),
 (924, 0.20953951903123735),
 (1121, 0.20953951903123735),
 (1231, 0.20953951903123735),
 (1331, 0.20892772350933625),
 (1332, 0.20892772350933625),
 (1010, 0.20851441405707477),
 (1305, 0.20851441405707477),
 (703, 0.20833333333333334),
 (731, 0.20833333333333334),
 (12, 0.20823168251814142),
 (262, 0.20823168251814142),
 (382, 0.20823168251814142),
 (389, 0.20823168251814142),
 (393, 0.20823168251814142),
 (397, 0.20823168251814142),
 (398, 0.20823168251814142),
 (375, 0.2082316825181414),
 (729, 0.2080125735844609),
 (1197, 0.2080125735844609),
 (1229, 0.2080125735844609),
 (787, 0.20626611516977106),
 (561, 0.20623947784607635),
 (606, 0.20623947784607635),
 (1233, 0.20623947784607635),
 (1281, 0.20623947784607635),
 (443, 0.20623947784607632),
 (453, 0.20623947784607632),
 (454, 0.20623947784607632),
 (456, 0.20623947784607632),
 (1028, 0.20623947784607632),
 (65, 0.20604084592303354),
 (141, 0.20573779994945587),
 (233, 0.20573779994945587),
 (425, 0.20573779994945587),
 (545, 0.20573779994945587),
 (900, 0.20573779994945587),
 (1002, 0.20573779994945587),
 (1234, 0.20573779994945587),
 (1239, 0.20573779994945587),
 (296, 0.20515248496555455),
 (826, 0.20515248496555455),
 (78, 0.2041241452319315),
 (1221, 0.2041241452319315),
 (282, 0.20361574059384205),
 (40, 0.20333142711013957),
 (1304, 0.20333142711013957),
 (48, 0.20309059861498083),
 (404, 0.20309059861498083),
 (626, 0.20309059861498083),
 (841, 0.20309059861498083),
 (519, 0.20225995873897262),
 (661, 0.20225995873897262),
 (211, 0.20123447664776561),
 (648, 0.20100756305184242),
 (676, 0.20100756305184242),
 (1310, 0.20100756305184242),
 (450, 0.20008168266626028),
 (407, 0.20008168266626025),
 (409, 0.20008168266626025),
 (410, 0.20008168266626025),
 (1029, 0.20008168266626025),
 (1032, 0.20008168266626025),
 (677, 0.2),
 (809, 0.2),
 (817, 0.2),
 (819, 0.2),
 (1296, 0.19920476822239894),
 (507, 0.1992047682223989),
 (1337, 0.1992047682223989),
 (1333, 0.19885291966710147),
 (993, 0.1987615979999813),
 (1097, 0.1987615979999813),
 (821, 0.19867985355975656),
 (829, 0.19867985355975656),
 (1336, 0.19867985355975654),
 (502, 0.19720265943665385),
 (560, 0.19720265943665385),
 (1026, 0.19720265943665385),
 (1241, 0.19720265943665385),
 (351, 0.19695964928958382),
 (1344, 0.19695964928958382),
 (755, 0.19658927487319616),
 (759, 0.19658927487319616),
 (1222, 0.19658927487319616),
 (400, 0.19655396472026238),
 (510, 0.19641855032959654),
 (576, 0.19641855032959654),
 (547, 0.196116135138184),
 (692, 0.196116135138184),
 (696, 0.196116135138184),
 (331, 0.19528336647123581),
 (345, 0.19528336647123581),
 (1027, 0.19528336647123581),
 (723, 0.1952833664712358),
 (982, 0.1952833664712358),
 (589, 0.19444444444444448),
 (706, 0.19444444444444448),
 (1048, 0.19444444444444448),
 (767, 0.19444444444444445),
 (869, 0.19444444444444445),
 (1006, 0.19444444444444445),
 (649, 0.19444444444444442),
 (217, 0.19364916731037082),
 (805, 0.19245008972987526),
 (806, 0.19245008972987526),
 (1283, 0.19245008972987526),
 (702, 0.19205531989934396),
 (973, 0.19179881852291683),
 (19, 0.1917988185229168),
 (322, 0.1917988185229168),
 (504, 0.1917988185229168),
 (1355, 0.1917988185229168),
 (1357, 0.1917988185229168),
 (1358, 0.1917988185229168),
 (327, 0.1911797782254681),
 (1162, 0.19050019050028577),
 (1170, 0.19050019050028574),
 (947, 0.19047619047619047),
 (1340, 0.18993429409939658),
 (1343, 0.18993429409939658),
 (395, 0.18925832465255626),
 (705, 0.18925832465255626),
 (738, 0.18925832465255626),
 (844, 0.18925832465255626),
 (1061, 0.18925832465255626),
 (808, 0.1889822365046136),
 (881, 0.1889822365046136),
 (907, 0.1889822365046136),
 (21, 0.18898223650461357),
 (108, 0.18898223650461357),
 (452, 0.18898223650461357),
 (455, 0.18898223650461357),
 (1017, 0.18898223650461357),
 (1051, 0.18898223650461357),
 (1077, 0.18898223650461357),
 (518, 0.18856180831641267),
 (983, 0.18856180831641267),
 (1277, 0.18856180831641267),
 (346, 0.18681617943926832),
 (1173, 0.18681617943926832),
 (310, 0.18670401120373462),
 (1124, 0.18670401120373462),
 (509, 0.18633899812498245),
 (517, 0.18633899812498245),
 (719, 0.18633899812498245),
 (244, 0.18569533817705186),
 (602, 0.18569533817705186),
 (932, 0.18569533817705186),
 (1113, 0.18569533817705186),
 (1127, 0.18569533817705186),
 (317, 0.1849000654084097),
 (1074, 0.1849000654084097),
 (548, 0.18463723646899907),
 (763, 0.18463723646899907),
 (422, 0.18446619684315546),

In [216]:
pred("Hammer Curls")

FYR Dumbbell Hammer Curl
Dumbbell Hammer Curl - Gethin Variation
AM Hammer Curls
Alternate Hammer Curl
TBS Hammer Curl

In [217]:
pred("FYR Banded Plank Jack")

Spider plank jack
Partner plank band row
Partner side plank band row
Plank up-down
Plank Push-Up

In [218]:
df["BodyPart"].unique()

array(['Abdominals', 'Abductors', 'Adductors', 'Biceps', 'Calves',
       'Chest', 'Forearms', 'Glutes', 'Hamstrings', 'Lats', 'Lower Back',
       'Middle Back', 'Traps', 'Quadriceps', 'Shoulders', 'Triceps'],
      dtype=object)

In [219]:
df[df["BodyPart"] == "Chest"]

,Title,Desc,Type,BodyPart,Equipment,Level,Actual_desc
438,Band-suspended kettlebell bench press,The band-suspended kettlebell bench press is a...,Strength,Chest,Bands,Intermediate,kettlebel bench press bench press variat kettl...
439,Incline band bench press,The incline band bench press is variation of t...,Strength,Chest,Bands,Intermediate,inclin band bench press variat inclin press po...
440,Band push-up,The band push-up is a progression of the popul...,Strength,Chest,Bands,Intermediate,band progress popular bodyweight version exerc...
441,Band chest fly,"Similar to the cable chest fly, the band chest...",Strength,Chest,Bands,Intermediate,similar cabl chest fli band chest fli movement...
442,Close-grip bench press,The close-grip bench press is a popular exerci...,Strength,Chest,Barbell,Intermediate,bench press popular exercis target tricep ches...
...,...,...,...,...,...,...,...
580,Bar Push-Up Smith Machine,The hands-elevated push-up is a variation on t...,Plyometrics,Chest,Other,Beginner,variat standard hand elev bodi align angl floo...
581,Plate-weighted push-up,The plate-weighted push-up is a simple way to ...,Strength,Chest,Other,Intermediate,simpl way make classic bodyweight exercis diff...
582,Double-bar roll-out chest fly,The double-bar roll-out chest fly is a chest e...,Strength,Chest,Other,Intermediate,chest fli chest exercis util two rotat barbel ...
583,Exercise ball chest stretch,The exercise ball chest stretch is a simple st...,Stretching,Chest,Exercise Ball,Beginner,exercis ball chest stretch simpl stretch pecto...
584,Feet-elevated push-up on ball,The feet-elevated push-up on ball is a variati...,Strength,Chest,Exercise Ball,Intermediate,ball variat bodyweight standard foot elev ball...

In [220]:
pred("Bench press")

Barbell Bench Press - Medium Grip
AM Flat Bench Barbell Press
UP Bench Press
King Maker Barbell Bench Press
Close-grip bench press

In [221]:
df[df["Title"] == "Single-arm dumbbell front squat"]

,Title,Desc,Type,BodyPart,Equipment,Level,Actual_desc
947,Single-arm dumbbell front squat,The single-arm dumbbell front squat is an exer...,Strength,Quadriceps,Dumbbell,Intermediate,dumbbel front squat exercis target quad glute ...

In [222]:
df[df["BodyPart"] == "Lats"]

,Title,Desc,Type,BodyPart,Equipment,Level,Actual_desc
680,Band-assisted pull-up,The band-assisted pull-up is a variation of th...,Strength,Lats,Bands,Intermediate,variat exercis rep perform elast band loop aro...
681,Assisted Chin-Up,The reverse-grip chin-up is a variation of the...,Strength,Lats,Bands,Beginner,variat exercis rep perform palm face toward bo...
682,Single-arm band low row,The single-arm band low row is a single-arm ro...,Strength,Lats,Bands,Intermediate,band low row row variat util band resist ancho...
683,Latissimus dorsi SMR,Latissimus dorsi self-myofascial release (SMR)...,Stretching,Lats,Foam Roll,Intermediate,latissimu dorsi releas smr treatment upper bod...
684,Bent-arm barbell pull-over,The bent-arm barbell pull-over was a staple ex...,Strength,Lats,Barbell,Intermediate,barbel stapl exercis golden era bodybuild favo...
...,...,...,...,...,...,...,...
744,Jump to pull-up,The jump to pull-up is a bodyweight exercise t...,Strength,Lats,Body Only,Intermediate,jump bodyweight exercis target muscl back bice...
745,Bent-over scapular slide,The bent-over scapular slide is an upper-body ...,Strength,Lats,Body Only,Intermediate,scapular slide exercis help scapular shoulder ...
746,Iron cross stretch,The iron cross stretch is a bodyweight stretch...,Strength,Lats,Body Only,Intermediate,iron cross stretch bodyweight stretch focus hi...
747,King Maker Pull-Up,The pull-up is a multi-joint bodyweight exerci...,Strength,Lats,Body Only,Intermediate,bodyweight exercis build strength muscl upper ...
748,Medicine ball slam,The medicine ball slam is an explosive exercis...,Plyometrics,Lats,Medicine Ball,Intermediate,medicin ball slam explos exercis develop power...

In [223]:
pred("Assisted Chin-Up")

Band-assisted chin-up
Band-assisted pull-up
Chin-Up
TBS Chin-Up
Neutral-grip pull-up

In [224]:
pred("Chin-Up")

TBS Chin-Up
Neutral-grip pull-up
Assisted Chin-Up
Band-assisted chin-up
Band-assisted pull-up

In [225]:
pred("Neutral-grip pull-up")

Chin-Up
TBS Chin-Up
Band-assisted pull-up
Assisted Chin-Up
Band-assisted chin-up

In [226]:
pred("Crunch")

Crunches
Crunch - Gethin Variation
Bent-knee reverse crunch
Cross-Body Crunch
Elbow-to-knee crunch

In [227]:
pred("Neutral-grip pull-up")

Chin-Up
TBS Chin-Up
Band-assisted pull-up
Assisted Chin-Up
Band-assisted chin-up

In [228]:
import re

results = Cleaned_df[
    Cleaned_df["Title"].str.contains(
        r"rep.*push|push.*rep",
        case=False,
        na=False
    )
]

print(results["Title"])

500    1.5-rep push-up
Name: Title, dtype: object

In [229]:
num_results = Cleaned_df[
    Cleaned_df["Title"].str.contains(
        r"\d",
        na=False
    )
]

print(num_results["Title"])

18      Kettlebell 3-point leg extension
100                           3/4 sit-up
500                      1.5-rep push-up
949                    3D dumbbell lunge
1021                90-degree jump squat
Name: Title, dtype: object

In [230]:
pred("1.5-rep push-up")

Pushups
FYR Push-Up
Push-Up - Gethin Variation
Push-up
UP Push-up

In [235]:
with open("workout.pkl","wb") as f:
    pickle.dump(Cleaned_df,f)

In [236]:
with open("similarity.pkl","wb") as f:
    pickle.dump(similarity,f)

In [237]:
with open("vectorizer.pkl","wb") as f:
    pickle.dump(Vectorizer,f)

In [238]:
with open("vectors.pkl","wb") as f:
    pickle.dump(vectors,f)